[buildPlans.custom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"

[buildPlans.custom.variants]
inherits = "ss04"

[buildPlans.custom.variants.design]
g = 'earless-corner'
k = 'curly'
v = 'curly'
w = 'curly'
capital-g = 'toothless-corner-serifless-hooked'
capital-q = 'crossing'
capital-r = 'curly'
capital-v = 'curly'
asterisk = 'low'
caret = 'low'
percent = 'rings-continuous-slash'

[buildPlans.custom.ligations]
enables = ["center-ops"]

[buildPlans.custom.widths.normal]
shape = 570 # default: 500, min: 434, max: 664
menu  = 5
css   = "normal"

[buildPlans.custom.widths.extended]
shape = 664 # default: 576, min: 434, max: 664
menu  = 9
css   = "expanded"
